# Generated by Django 5.0.6 on 2024-05-28 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminMain', '0005_alter_category_categoryname'),
        ('farmerAuth', '0003_alter_farmers_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(auto_created=True)),
                ('cropName', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('quickSale', models.BooleanField(default=False)),
                ('isDelete', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminMain.category')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerAuth.farmers')),
            ],
        ),
        migrations.CreateModel(
            name='Cropimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='crops/')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerMain.crops')),
            ],
        ),
    ]
