# Generated by Django 5.0.6 on 2024-05-29 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerMain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropimage',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='farmerMain.crops'),
        ),
    ]
