# Generated by Django 5.0.6 on 2024-05-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerMain', '0002_alter_cropimage_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='crops',
            name='About',
            field=models.TextField(default='adf'),
            preserve_default=False,
        ),
    ]
