# Generated by Django 5.0.6 on 2024-06-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerMain', '0003_crops_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crops',
            name='createdAt',
            field=models.DateField(auto_now_add=True),
        ),
    ]
