# Generated by Django 5.0.6 on 2024-06-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerMain', '0004_alter_crops_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='crops',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
