# Generated by Django 5.0.6 on 2024-06-13 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMain', '0005_alter_category_categoryname'),
        ('farmerAuth', '0003_alter_farmers_user'),
        ('farmerMain', '0006_cropreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crops',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='AdminMain.category'),
        ),
        migrations.AlterField(
            model_name='crops',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer', to='farmerAuth.farmers'),
        ),
    ]
