# Generated by Django 5.0.6 on 2024-05-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.BigIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
