# Generated by Django 5.0.6 on 2024-05-29 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerProfile', '0003_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='Email',
        ),
    ]
