# Generated by Django 5.0.6 on 2024-06-03 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerProfile', '0005_follower'),
        ('farmerAuth', '0003_alter_farmers_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('user', 'farmer')},
        ),
        migrations.AddField(
            model_name='follower',
            name='followed_at',
            field=models.DateField(auto_now_add=True, default='2024-03-04'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='follower',
            name='is_followed',
        ),
    ]
