# Generated by Django 5.0.6 on 2024-06-04 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerProfile', '0006_alter_follower_unique_together_follower_followed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='subtotal',
        ),
    ]
