# Generated by Django 5.0.6 on 2024-06-04 17:28

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerProfile', '0007_remove_cart_subtotal'),
        ('farmerMain', '0006_cropreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_name', models.CharField(max_length=50)),
                ('shipping_price', models.IntegerField()),
                ('des', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False, null=True)),
                ('paid_amount', models.CharField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='first_name', unique=True)),
                ('total', models.CharField(max_length=260)),
                ('is_deleted', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[('cash_on_delivery', 'Cash on Delivery'), ('pay_by_wallet', 'Wallet  payment'), ('paypal', 'PayPal')], max_length=50, null=True)),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customerProfile.shippingaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_total', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='order', unique=True)),
                ('total', models.CharField(null=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerMain.crops')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='customerProfile.order')),
                ('shipping_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customerProfile.shipping')),
            ],
        ),
    ]
