# Generated by Django 5.0.6 on 2024-06-08 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerProfile', '0008_shipping_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='Phone_number',
        ),
    ]
