# Generated by Django 5.0.6 on 2024-06-09 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerProfile', '0009_remove_shippingaddress_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='shipping_option',
        ),
        migrations.DeleteModel(
            name='shipping',
        ),
    ]
