# Generated by Django 5.0.6 on 2024-06-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerProfile', '0012_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='sub_total',
            field=models.CharField(),
        ),
    ]
