# Generated by Django 5.0.6 on 2024-07-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerProfile', '0013_alter_orderitem_sub_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on delivery', 'Cash on Delivery'), ('wallet', 'Wallet  payment'), ('paypal', 'PayPal')], max_length=50, null=True),
        ),
    ]
