# Generated by Django 5.0.6 on 2024-07-09 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerProfile', '0015_order_farmer'),
        ('farmerAuth', '0003_alter_farmers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmerorder', to='farmerAuth.farmers'),
        ),
    ]
