# Generated by Django 5.0.6 on 2024-10-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerProfile', '0016_alter_order_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='farmer_accept',
            field=models.BooleanField(default=False),
        ),
    ]
