# Generated by Django 5.2.8 on 2026-02-18 15:09

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerProfile', '0017_order_farmer_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='order.slug', unique=True),
        ),
    ]
