# Generated by Django 5.2.8 on 2026-02-18 16:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerProfile', '0018_alter_orderitem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='slug',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
