# Generated by Django 5.0.6 on 2024-05-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMain', '0002_alter_category_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
