# Generated by Django 5.0.6 on 2024-05-15 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMain', '0003_category_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='about',
            field=models.TextField(default='friut'),
            preserve_default=False,
        ),
    ]
