# Generated by Django 5.0.6 on 2024-05-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMain', '0004_category_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryName',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
