# Generated by Django 5.0.4 on 2024-04-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone_number', models.IntegerField()),
                ('is_farmer', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('Address', models.TextField()),
                ('Country', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('District', models.CharField(max_length=50)),
                ('postal_code', models.IntegerField()),
                ('is_blocked', models.BooleanField()),
                ('Created_at', models.DateField(auto_now_add=True)),
                ('groups', models.ManyToManyField(related_name='custom_user_accounts_groups', related_query_name='user_accounts_group', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='custom_user_accounts_permissions', related_query_name='user_accounts_permission', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
