# Generated by Django 5.0.4 on 2024-04-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='Address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='Country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='District',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='State',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='is_blocked',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='postal_code',
            field=models.IntegerField(null=True),
        ),
    ]
