# Generated by Django 5.0.4 on 2024-04-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerAuth', '0003_rename_is_farmer_customers_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='is_blocked',
            field=models.BooleanField(default=True),
        ),
    ]
