# Generated by Django 5.0.4 on 2024-05-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('customerAuth', '0005_alter_customers_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_accounts_groups', related_query_name='user_accounts_group', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_accounts_permissions', related_query_name='user_accounts_permission', to='auth.permission'),
        ),
    ]
