# Generated by Django 5.0.6 on 2024-05-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerAuth', '0010_customers_otp_alter_customers_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='Phone_number',
            field=models.BigIntegerField(),
        ),
    ]
