# Generated by Django 5.0.6 on 2024-05-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerAuth', '0011_alter_customers_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='registration_method',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google')], default='email', max_length=10),
        ),
    ]
