# Generated by Django 5.0.6 on 2024-05-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerAuth', '0012_customers_registration_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
