# Generated by Django 5.0.6 on 2024-05-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerAuth', '0013_customers_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='Phone_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
