# Generated by Django 5.0.4 on 2024-04-30 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_of_birth', models.DateField()),
                ('Location', models.CharField(max_length=50)),
                ('Bio', models.TextField()),
                ('farmer_photo', models.ImageField(upload_to='farmer/')),
                ('is_paid', models.BooleanField(default=False)),
                ('Can_sell', models.BooleanField(default=False)),
                ('longitude', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
