# Generated by Django 5.0.6 on 2024-05-18 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerAuth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CultingCrops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cropname', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeildPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feild_photo', models.ImageField(null=True, upload_to='feild/')),
            ],
        ),
        migrations.RemoveField(
            model_name='farmers',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='farmers',
            name='longitude',
        ),
        migrations.AddField(
            model_name='farmers',
            name='cultivatingCrop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farmerAuth.cultingcrops'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmers',
            name='feildPhoto',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='farmerAuth.feildphotos'),
            preserve_default=False,
        ),
    ]
