# Generated by Django 5.0.6 on 2024-07-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerAuth', '0004_farmerreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerreview',
            name='reviwe',
        ),
        migrations.AddField(
            model_name='farmerreview',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='farmerreview',
            name='review',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
